server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: reservations-service
          uri: lb://reservations-service
          predicates:
            - Path=/api/reservations/**
        - id: pickup-service
          uri: lb://pickup-service
          predicates:
            - Path=/api/pickup/**

eureka:
  client:
    service-url:
      defaultZone: http://naming-server:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
    httpclient:
      enabled: true
